const DB_NAME = 'migration_profiles';
const DB_VERSION = 1;
const PROFILE_STORE_NAME = 'profiles';
const PROFILE_SCRIPTS_STORE_NAME = 'profileScripts';

export interface MigrationProfile {
    name: string,
    config: WorkflowMigrationConfig
}

export interface MigrationConfig {
    sourceDB: string,
    targetDB: string,
    
    /**
     * Whether to update existing records with updated values
     */
    syncExisting: boolean,
}

export interface WorkflowMigrationConfig extends MigrationConfig {
    /**
     * R4 workflow type of the workflow to migrate data from
     */
    workflowType: string,
    /**
     * Omega 365 process ID of the scope item to migrate data to
     */
    processID: number,
    /**
     * R4 workflow base table name
     */
    baseTable:string,

    /**
     * The R4 workflow type revision this config is applicable to, leave empty if it applies to all revisions
     */
    applicableRevisions: number[],

    stepsMapping: WorkflowStepsMapping[],
    rolesMapping: WorkflowRoleMapping[],
    signaturesMapping: WorkflowSignatureMapping[],
    metadataMapping: WorkflowMetadataMapping[],
}

export interface WorkflowStepsMapping {
    r4Step: number,
    o365Step: number,
}

export interface WorkflowRoleMapping {
    r4RoleCode: string,
    o365RoleID: string,
}

export interface WorkflowSignatureMapping {
    r4Step: number,
    o365Step: number,
    r4RoleCode: string,
    migrateAs: 'step responsible' | 'verification' | 'review' | 'comment'
}

export interface WorkflowMetadataMapping {
    /**
     * the column name of the column that contains the data to migrate from the R4 base table or a lookup table 
     */
    r4FieldName: string,
    
    /**
     * the base field name of the scope item, or a property name for the data to migrate to in Omega 365
     */
    o365FieldName: string,

    //TODO: add details for the mapping
}

export interface MigrationScript {
    profileName: string,
    scriptName: string,
    script: string,
}

function openDatabase(): Promise<IDBDatabase> {
	return new Promise((resolve, reject) => {
		const request = indexedDB.open(DB_NAME, DB_VERSION)

		request.onupgradeneeded = () => {
			const database = request.result
            
            //initialize the object stores if they don't exist
            if (!database.objectStoreNames.contains(PROFILE_STORE_NAME)) {
				database.createObjectStore(PROFILE_STORE_NAME, { keyPath: 'name' })
			}

			if (!database.objectStoreNames.contains(PROFILE_SCRIPTS_STORE_NAME)) {
				database.createObjectStore(PROFILE_SCRIPTS_STORE_NAME, { keyPath: ['profileName', 'scriptName'] })
			}
		}

		request.onsuccess = () => {
			resolve(request.result)
		}

		request.onerror = () => {
			reject(request.error ?? new Error('Failed to open IndexedDB database.'))
		}
	})
}

function runStoreRequest<T>(
	database: IDBDatabase,
    storeName: string,
	mode: IDBTransactionMode,
	operation: (store: IDBObjectStore) => IDBRequest<T>
): Promise<T> {
	return new Promise((resolve, reject) => {
		const transaction = database.transaction(storeName, mode)
		const store = transaction.objectStore(storeName)
		const request = operation(store)

		request.onsuccess = () => {
			resolve(request.result)
		}

		request.onerror = () => {
			reject(request.error ?? new Error('IndexedDB request failed.'))
		}
	})
}

/**
 * Manages loading and saving of migration profiles.
 * 
 * Migration profiles are stored in the browser inside IndexedDB.
 * Each profile contains configurations and a set of scripts generated by it.
 */
const profileManager = {
    saveProfile: async (profile: MigrationProfile): Promise<IDBValidKey> => {
        const database = await openDatabase();
        return runStoreRequest(database, PROFILE_STORE_NAME, 'readwrite', store => store.put(profile));
    },

    deleteProfile: async (profileName: string): Promise<void> => {
        const database = await openDatabase();
        return runStoreRequest(database, PROFILE_STORE_NAME, 'readwrite', store => store.delete(profileName));
    },

    getProfile: async (profileName: string): Promise<MigrationProfile | undefined> => {
        const database = await openDatabase();
        return runStoreRequest(database, PROFILE_STORE_NAME, 'readonly', store => store.get(profileName));
    },

    getProfiles: async (): Promise<MigrationProfile[]> => {
        const database = await openDatabase();
        return runStoreRequest(database, PROFILE_STORE_NAME, 'readonly', store => store.getAll());
    },

    saveProfileScript: async (script: MigrationScript): Promise<IDBValidKey> => {
        const database = await openDatabase();
        return runStoreRequest(database, PROFILE_SCRIPTS_STORE_NAME, 'readwrite', store => store.put(script));
    }, 

    deleteProfileScript: async (profileName: string, scriptName: string): Promise<void> => {
        const database = await openDatabase();
        return runStoreRequest(database, PROFILE_SCRIPTS_STORE_NAME, 'readwrite', store => store.delete([profileName, scriptName]));
    },

    getProfileScript: async (profileName: string, scriptName: string): Promise<MigrationScript | undefined> => {
        const database = await openDatabase();
        return runStoreRequest(database, PROFILE_SCRIPTS_STORE_NAME, 'readonly', store => store.get([profileName, scriptName]));
    },

    getProfileScripts: async (profileName: string): Promise<MigrationScript[]> => {
        const database = await openDatabase();
        return runStoreRequest(database, PROFILE_SCRIPTS_STORE_NAME, 'readonly', store => store.getAll(IDBKeyRange.bound([profileName], [profileName, []])));
    },
}

export default profileManager;